### ISSUE TITLE
Feature reqeust

### ISSUE THREAD

**Issue by granin** [jasonrudolph/keyboard#15]
Is it possible to have the option to assign Caps not to ESC / Ctrl but to ESC / Hyper key (Ctrl + Alt + Cmd), here I saw it's possible with your toolset: 
http://brettterpstra.com/2016/09/29/a-better-hyper-key-hack-for-sierra/

**Comment by jasonrudolph** [comment]
:wave: @granin: I think it might be possible to map caps lock to escape/hyper.

To make sure that I can continue getting personal enjoyment from working on this repo, [I'm only adding features that I would personally use](https://github.com/jasonrudolph/keyboard/tree/6e262992a1d76d9efff8aaf99981cf7e2729a762#more-useful-for-me). This isn't a feature that I see myself using, so I probably won't add it. However, you might consider forking the repo and adding this customization to your fork. In case it helps, I can point you at the relevant parts of the code:

- [`karabiner/karabiner.json`](https://github.com/jasonrudolph/keyboard/blob/6e262992a1d76d9efff8aaf99981cf7e2729a762/karabiner/karabiner.json#L37-L40) currently maps **caps lock** to **left control** and maps **right option** to **F17**.
- [`hammerspoon/hyper.lua`](https://github.com/jasonrudolph/keyboard/blob/6e262992a1d76d9efff8aaf99981cf7e2729a762/hammerspoon/hyper.lua#L32-L33) binds custom behavior to **F17**.
- [`hammerspoon/control-escape.lua`](https://github.com/jasonrudolph/keyboard/blob/6e262992a1d76d9efff8aaf99981cf7e2729a762/hammerspoon/control-escape.lua) makes it so that *tapping* **control** triggers **escape**.
