### ISSUE TITLE
Enter "Super-Duper" mode with a single keystroke

### ISSUE THREAD

**Issue by danielinfuse** [jasonrudolph/keyboard#66]
Is it possible to enter the Super Duper mode with just a single "s" or "d" keystroke? It will be helpful because Mac keyboard cannot do N-key rollover (only 6 I believe). Also I find it pretty tiring to hold 2 fingers (ring and middle fingers) to enter the mode.

I'm looking at the super.lua file right now but since I don't know lua, I have not been able to modify it.

**Comment by jasonrudolph** [comment]
👋 Hi @danielinfuse: If you fork the repository and change the code, then you could customize it to enter (S)uper (D)uper Mode with a single keystroke. You'll likely need to try your hands at a bit of Lua to make it work, but it should be do-able.

To get started, you could look at the code for [Markdown Mode](https://github.com/jasonrudolph/keyboard/tree/3bee475a114f2e2697d536676d96f77bafb26b2e#markdown-mode), which is triggered with a single keystroke (<kbd>control</kbd> + <kbd>m</kbd>) here:

https://github.com/jasonrudolph/keyboard/blob/3bee475a114f2e2697d536676d96f77bafb26b2e/hammerspoon/markdown.lua#L106-L112

You could use a similar approach to change [`super.lua`](https://github.com/jasonrudolph/keyboard/blob/v5.0.0/hammerspoon/super.lua) to trigger (S)uper (D)uper Mode with a single keystroke. It will be a bit of work, but it's do-able if you put your mind to it. 😅

Since I [personally prefer](https://github.com/jasonrudolph/keyboard/tree/3bee475a114f2e2697d536676d96f77bafb26b2e#more-useful-for-me) using the <kbd>s</kbd> + <kbd>d</kbd> keys to trigger (S)uper (D)uper Mode, it's unlikely that I'll change this functionality, but I hope the pointer above is helpful.
