### ISSUE TITLE
Moving windows to a different space

### ISSUE THREAD

**Issue by BasilPH** [jasonrudolph/keyboard#70]
I can move windows to a different monitor, but not to a different space.

The native shortcut to move to a different space is `ctrl` +  `→`/`←`.

Copying GNOME, we could use `ctrl` + `shift` + `→`/`←` to move to a screen and take the active window with us?

**Comment by jasonrudolph** [comment]
👋 @BasilPH: Thanks for the idea. I don't personally use spaces. I'm not actually sure why. They just never seemed to find their way into my workflow.

To make sure that I can continue getting personal enjoyment from working on this repo, [I'm only adding features that I would personally use](https://github.com/jasonrudolph/keyboard/tree/6e262992a1d76d9efff8aaf99981cf7e2729a762#more-useful-for-me). Since this isn't a feature that I see myself using, I probably won't add it. However, [MoveSpaces.spoon](https://github.com/Hammerspoon/Spoons/blob/cf9e4044e146382683e7f5873512aea41d7fe728/Spoons/MoveSpaces.spoon.zip) might provide what you're looking for, and you can find info on installing and using spoons [here](https://github.com/Hammerspoon/hammerspoon/blob/3fa87b10ee3f1737bfa4bf434bbbd4cb6282e945/SPOONS.md#how-do-i-install-a-spoon).

I hope this helps.

**Comment by BasilPH** [comment]
Hi @jasonrudolph, thank you for your quick response. Fair enough, I'll gladly check out the spoon you linked.

Very cool project btw, I use it constantly.
